name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Generate Snake animation (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: 14miguels
          outputs: dist/snake-dark.svg
          color_snake: "#1E90FF"
          color_dots: "#0D1117,#161B22,#30363D,#58A6FF,#1E90FF"

      - name: Push Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
