name: Generate Snake

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"   # todos os dias à meia-noite UTC
  workflow_dispatch:

# Garante que o token tem escrita (mesmo que as definições do repo não estejam certas)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gera os SVGs (normal e dark). Este é o modo recomendado "svg-only".
      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 14miguels
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&color_snake=#1E90FF

      # Publica os ficheiros em branch "output/dist/*"
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
